# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='书名')),
                ('pub', models.CharField(max_length=20, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('marker_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='零售价')),
            ],
        ),
    ]
